spryk: method
description: "Adds a new resource mapper method to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  fromTransfer:
    inherit: true
    default: "Rest{{ resourceType | dashToCamelCase }}AttributesTransfer"

  toTransfer:
    inherit: true
    default: "Rest{{ resourceType | dashToCamelCase }}AttributesTransfer"

  method:
    value: "map{{ fromTransfer }}To{{ toTransfer }}"
    inherit: true

  target:
    value: "{{ organization }}\\Glue\\{{ module }}\\Processor\\Mapper\\{{ resourceType | singularize | dashToCamelCase | ensureMapperSuffix}}"

  template:
    value: Glue/Processor/Mapper/GlueResourceMapperMethod.php.twig

preSpryks:
  - AddModule
  - AddSharedRestAttributesTransfer:
      arguments:
        name:
          value: "{{ resourceType | dashToCamelCase }}"
          callback:
            - EnsureRestAttributesTransferAffix
  - AddGlueProcessorModel:
      arguments:
        className:
          value: "{{ resourceType | singularize | dashToCamelCase }}Mapper"
        subDirectory:
          value: "Mapper"

postSpryks:
  - AddGlueProcessorModelInterfaceMethod:
      arguments:
        method:
          value: "map{{ fromTransfer }}To{{ toTransfer }}"
        subDirectory:
          value: "Mapper"
        input:
          value: "\\Generated\\Shared\\Transfer\\{{ fromTransfer }} ${{ fromTransfer | lcfirst }}, \\Generated\\Shared\\Transfer\\{{ toTransfer }} ${{ toTransfer | lcfirst }}"
        output:
          value: "\\Generated\\Shared\\Transfer\\{{ toTransfer }}"
