spryk: template
description: "Adds a new *moduleName* DependencyProvider to the Yves application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Yves/YvesDependencyProvider.php.twig

  targetFilename:
    value: "{{ moduleName }}DependencyProvider.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Yves/{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule
