spryk: template
description: "Adds a new *moduleName*Config to the Yves application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Yves/YvesConfig.php.twig

  targetFilename:
    value: "{{ moduleName }}Config.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Yves/{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
