spryk: template
description: "Adds a new *module*Config to the Yves application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Yves/YvesConfig.php.twig

  targetFilename:
    value: "{{ module }}Config.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Yves/{{ module }}/"

preSpryks:
  - CreateSprykerModule
