spryk: template
description: "Adds a new *moduleName* Factory to the Yves application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Yves/YvesFactory.php.twig

  targetFilename:
    value: "{{ moduleName }}Factory.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Yves/{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedBusinessFacade
  - AddYvesDependencyProvider
  - AddZedConfig
