spryk: method
description: "Adds a new method to the Yves *module*Config."

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Method.php.twig

  target:
    value: "{{ organization }}\\Yves\\{{ module }}\\{{ module }}Config"

preSpryks:
  - AddYvesConfig

