spryk: template
description: "Adds a new *module*Config to the Yves application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: YvesConfig.php.twig

  targetFilename:
    value: "%module%Config.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Yves/%module%/"

preSpryks:
  - CreateSprykerModule
