language: php

sudo: false

php:
    - 7.1

install:
    - composer self-update
    - composer remove --dev spryker/git-hook
    - composer install --optimize-autoloader --no-interaction

script:
    - vendor/bin/codecept run --coverage-xml
    - vendor/bin/phpstan analyse src/ -l 7 -c phpstan.neon
    - vendor/bin/phpcs src -v -s --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml
    - vendor/bin/phpcs tests -v -s --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml

notifications:
    email: false

after_success:
    - travis_retry php vendor/bin/coveralls
