spryk: method
arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  method: ~
  inputType: ~
  inputVariable: ~
  outputType: ~

  specification:
    default: "ADD SPECIFICATION HERE"

  template:
    value: InterfaceMethod.php.twig

  target:
    value: "%moduleOrganization%\\Client\\%module%\\%module%ClientInterface"

preSpryks:
  - AddClientInterface
