spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ClientDependencyProvider.php.twig

  targetFilename:
    value: %module%DependencyProvider.php

  targetPath:
    default: vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Client/%module%/

preSpryks:
  - CreateModule
