spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: codeception.yml.twig

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/"

preSpryks:
  - CreateModule
