spryk: template

arguments:
  module: ~

  repositoryToken: ~

  template:
    value: coveralls.yml.twig

  targetFilename:
      value: .coveralls.yml

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/"

preSpryks:
  - CreateModule
