spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: Client.php.twig

  targetFilename:
    value: "%module%Client.php"

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Client/%module%/"

preSpryks:
  - CreateModule

postSpryks:
  - AddClientInterface
  - AddClientFactory
