spryk: method
arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  method: ~
  inputType: ~
  inputVariable: ~
  outputType: ~

  specification:
    default: "ADD SPECIFICATION HERE"

  template:
    value: FacadeInterfaceMethod.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Business\\%module%FacadeInterface"

preSpryks:
  - AddFacadeInterface
