spryk: method
arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  method: ~
  inputType: ~
  inputVariable: ~
  outputType: ~

  template:
    value: FacadeMethod.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Business\\%module%Facade"

preSpryks:
  - AddFacade

postSpryks:
  - AddFacadeInterfaceMethod
