spryk: template

arguments:
  module: ~

  template:
    value: gitignore.twig

  targetFilename:
    value: .gitignore

  targetPath:
    default: vendor/spryker/spryker/Bundles/%module%/

preSpryks:
  - CreateModule
