spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: README.md.twig

  targetPath:
    default: vendor/spryker/spryker/Bundles/%module%/

preSpryks:
  - CreateModule
