spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: SharedConstantsInterface.php.twig

  targetFilename:
    value: "%module%Constants.php"

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Shared/%module%/"

preSpryks:
  - CreateModule
