spryk: template

arguments:
  module: ~

  template:
    value: scrutinizer.yml.twig

  targetFilename:
    value: .scrutinizer.yml

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/"

preSpryks:
  - CreateModule
