spryk: template

arguments:
  module: ~

  template:
    value: travis.yml.twig

  targetFilename:
    value: .travis.yml

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/"

preSpryks:
  - CreateModule
