spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedRepositoryInterface.php.twig

  targetFilename:
    value: "%module%RepositoryInterface.php"

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Zed/%module%/Persistence/"

preSpryks:
  - AddZedRepository
