spryk: template
description: "Adds a new *module*EntityManager to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedEntityManager.php.twig

  targetFilename:
    value: "%module%EntityManager.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Persistence/"

preSpryks:
  - CreateModule

postSpryks:
  - AddZedEntityManagerInterface
