spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedEntityManagerInterface.php.twig

  targetFilename:
    value: "%module%EntityManagerInterface.php"

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Zed/%module%/Persistence/"

preSpryks:
  - AddZedEntityManager

