spryk: method
arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  className: ~
  # Spryker\Zed\FooBar\Business\Model\FooBar

  returnType:
    default: "%className%Interface"

  method:
    callbackOnly: true
    callback: ZedBusinessFactoryMethodNameCallback

  template:
    value: MethodBusinessFactory.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Business\\%module%BusinessFactory"

preSpryks:
  - AddZedBusinessFactory

