spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedCommunicationFactory.php.twig

  targetFilename:
    value: %module%CommunicationFactory.php

  targetPath:
    default: vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Zed/%module%/Communication/

preSpryks:
  - CreateModule
