spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedQueryContainer.php.twig

  targetFilename:
    value: "%module%QueryContainer.php"

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Zed/%module%/Persistence/"

preSpryks:
  - CreateModule

postSpryks:
  - AddZedQueryContainerInterface

