spryk: template

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  controller:
    default: Index

  template:
    value: ZedController.php.twig

  targetFilename:
    value: "%controller%Controller.php"

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Zed/%module%/Communication/Controller/"

preSpryks:
  - CreateModule

