spryk: template
description: "Adds a new *module*PersistenceFactory to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedPersistenceFactory.php.twig

  targetFilename:
    value: "%module%PersistenceFactory.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Persistence/"

preSpryks:
  - CreateModule

