spryk: template
description: "Adds a new *module*Facade to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedFacade.php.twig

  targetFilename:
    value: "%module%Facade.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Business/"

preSpryks:
  - CreateModule

postSpryks:
  - AddZedFacadeInterface
  - AddZedBusinessFactory
