spryk: template
description: "Adds a new *module*CommunicationFactory to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedCommunicationFactory.php.twig

  targetFilename:
    value: "%module%CommunicationFactory.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Communication/"

preSpryks:
  - CreateModule
