spryk: template

arguments:
  module: ~
  moduleOrganization:
    default: Spryker

  template:
    value: navigation.xml.twig

  targetPath:
    default: "vendor/spryker/spryker/Bundles/%module%/src/%moduleOrganization%/Zed/%module%/Communication/"

preSpryks:
  - CreateModule
