spryk: structure

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  targetPath:
    default: vendor/spryker/spryker/Bundles/%module%/

  directories:
    value:
      - src/

postSpryks:
  - AddReadme
  - AddComposerJson
  - AddLicense
  - AddContributing
  - AddChangelog
