spryk: structure
description: "Adds a new GET Resource to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  modelName:
    inherit: true
    default: "{{ resourceType }}"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

  directories:
    value:
      - ""

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResource:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase }}Resource"
        interfaceName:
          value: "{{ resourceType | dashToCamelCase }}ResourceInterface"
  - AddGlueResourceRoute:
      arguments:
        modelSuffix:
          value: "Reader"
        resourceRouteMethod:
          value: "get"