spryk: template
description: "Adds a new Glue *module*Config."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Glue/GlueConfig.php.twig

  targetFilename:
    value: "{{ module }}Config.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
  - AddModule
