spryk: structure
description: "Adds a new POST Resource to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

  directories:
    value:
      - ""

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResourceRoute:
      arguments:
        modelSuffix:
          value: "Creator"
        resourceRouteMethod:
          value: "post"
  - AddGlueControllerPostAction:
      arguments:
        controllerMethod:
          value: "{{ resourceRouteMethod }}"
          callback: EnsureActionSuffixCallback
        controller:
          value: "{{ resourceType | dashToCamelCase }}"
          callback: EnsureResourceSuffix
        target:
          value: "{{ organization }}\\Glue\\{{ module }}\\Controller\\{{ resourceType | dashToCamelCase }}"
          callback:
            - EnsureResourceSuffix
            - EnsureControllerSuffixCallback
