spryk: structure
description: "Adds a new PATCH Resource to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  modelName:
    inherit: true
    default: "{{ resourceType }}"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

  directories:
    value:
      - ""

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResource:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase }}"
          callback: EnsureResourceSuffix
        interfaceName:
          value: "{{ resourceType | dashToCamelCase }}"
          callback:
            - EnsureResourceSuffix
            - EnsureInterfaceSuffix
  - AddGlueResourceRoute:
      arguments:
        modelSuffix:
          value: "Updater"
        resourceRouteMethod:
          value: "patch"
  - AddGlueControllerPatchAction:
      arguments:
        method:
          value: "{{ resourceRouteMethod }}"
          callback: EnsureActionSuffixCallback
        controller:
          value: "{{ resourceType | dashToCamelCase }}"
          callback: EnsureResourceSuffix
        target:
          value: "{{ organization }}\\Glue\\{{ module }}\\Controller\\{{ resourceType | dashToCamelCase }}"
          callback:
            - EnsureResourceSuffix
            - EnsureControllerSuffixCallback