spryk: structure
description: "Adds a new Glue layer with basic structure."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  targetPath:
    value: "{{ module }}/"

  directories:
    value:
      - "src/{{ organization }}/"

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResourceRoutePlugin
  - AddGlueResourceMapper:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase | singularize }}Mapper"
  - AddGlueController:
      arguments:
        controller:
          value: "{{ resourceType | dashToCamelCase }}ResourceController"
  - AddGlueResourceRestResponseBuilderModel:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilder"
        interfaceName:
          value: "{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilderInterface"
        subDirectory:
          value: "RestResponseBuilder"

