spryk: structure
description: "Adds a new Glue layer with basic structure."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  fromTransfer:
    inherit: true

  clientModule:
    inherit: true

  clientMethod:
    inherit: true

  clientMethodInput:
    inherit: true
    optional: true
    isMultiple: true

  clientMethodOutput:
    inherit: true

  targetPath:
    value: "{{ module }}/"

  directories:
    value:
      - "src/{{ organization }}/"

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResourceRoutePlugin
  - AddGlueController:
      arguments:
        controller:
          value: "{{ resourceType | dashToCamelCase | singularize }}ResourceController"
  - AddGlueResourceMapper:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase | singularize }}Mapper"
        subDirectory:
          value: "Mapper"
  - AddGlueResourceMapperMethod
  - AddGlueResourceMapperInterfaceMethod
  - AddGlueResourceRestResponseBuilderModel:
      arguments:
        className:
          value: "{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilder"
        interfaceName:
          value: "{{ resourceType | dashToCamelCase | singularize }}RestResponseBuilderInterface"
        subDirectory:
          value: "RestResponseBuilder"
  - AddGlueDependencyClientBridge:
      arguments:
        dependentModule:
          value: "{{ clientModule }}"
  - AddGlueDependencyClientBridgeMethod:
      arguments:
        dependentModule:
          value: "{{ clientModule }}"
        methods:
          value: [ "{{ clientMethod }}" ]
  - AddGlueDependencyClientBridgeInterfaceMethod:
      arguments:
        dependentModule:
          value: "{{ clientModule }}"
        methods:
          value: [ "{{ clientMethod }}" ]

