spryk: template
description: "Adds a new Glue resource interface."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Glue/GlueResourceInterface.php.twig

  targetFilename:
    value: "{{ module }}ResourceInterface.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}"

preSpryks:
  - AddModule
