spryk: structure
description: "Adds a new GET Resource relationship to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  resourceType:
    inherit: true

  field:
    inherit: true

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

  directories:
    value:
      - ""

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResourceRelationshipPlugin
