spryk: template
description: "Adds a new Resource to the Glue application."
mode: both

application: Glue

priority: 1

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  className:
    inherit: true

  interfaceName:
    inherit: true
    default: "{{ className }}Interface"

  template:
    value: Glue/GlueResource.php.twig

  targetFilename:
    callbackOnly: true
    callback: GlueResourceTargetFilename

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
  - AddModule

postSpryks:
  - AddGlueResourceInterface
