spryk: template
description: "Adds a new *moduleName* To*dependentModule*FacadeInterface."

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  dependentModule:
    moduleFilter:
      application: Zed

  organization:
    default: Spryker

  template:
    value: Zed/Dependency/Facade/ZedDependencyFacadeInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}FacadeInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Dependency/Facade/"

preSpryks:
  - AddZedDependencyFacadeBridge
