spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency facade bridge."
priority: 1

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  organization:
    default: Spryker

  dependentModule:
    moduleFilter:
      application: Zed

  methods:
    type: MethodNameChoice
    choiceLoader: ZedFacadeMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - moduleName
      - choiceLoader

  template:
    value: Zed/Dependency/ZedDependencyBridgeMethod.php.twig

  dependencyType:
    value: Facade

  sourceClass:
    value: "{{ organization }}\\Zed\\{{ dependentModule }}\\Business\\{{ dependentModule }}Facade"

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Dependency\\Facade\\{{ moduleName }}To{{ dependentModule }}FacadeBridge"

preSpryks:
  - AddZedBusinessFacade
  - AddZedDependencyFacadeBridge

postSpryks:
  - AddZedDependencyFacadeBridgeInterfaceMethod
