spryk: template
description: "Adds a new *moduleName* To*dependentModule*FacadeBridge."

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  organization:
    default: Spryker

  dependentModule:
    moduleFilter:
      application: Zed

  dependentModuleOrganization:
    default: Spryker


  template:
    value: Zed/Dependency/Facade/ZedDependencyFacadeBridge.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}FacadeBridge.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Dependency/Facade/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedDependencyFacadeInterface
  - AddZedDependencyFacadeBusinessFactoryMethod
  - AddZedDependencyFacadeDependencyProviderMethod
  - AddZedDependencyFacadeDependencyProviderConstant:
      arguments:
          name:
            value: "FACADE_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} facade"
          visibility:
            value:  "public"
