spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency facade bridge interface."

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  organization:
    default: Spryker

  dependentModule:
    moduleFilter:
      application: Zed

  methods:
    type: MethodNameChoice
    choiceLoader: ZedFacadeMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - module
      - choiceLoader

  template:
    value: Zed/Dependency/ZedDependencyBridgeInterfaceMethod.php.twig

  dependencyType:
    value: Facade

  sourceClass:
    value: "{{ organization }}\\Zed\\{{ dependentModule }}\\Business\\{{ dependentModule }}FacadeInterface"

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Dependency\\Facade\\{{ moduleName }}To{{ dependentModule }}FacadeInterface"

preSpryks:
  - AddZedDependencyFacadeInterface

postSpryks:
  - AddZedDependencyFacadeBridgeMethod


