spryk: template
description: "Adds a new CHANGELOG.md to the Modules root."

arguments:
  module: ~

  template:
    value: CHANGELOG.md.twig

  targetPath:
    default: "%module%/"

preSpryks:
  - CreateModule
