spryk: template
description: "Adds a new *Module*Client to the Client application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: Client.php.twig

  targetFilename:
    value: "%module%Client.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Client/%module%/"

preSpryks:
  - CreateModule

postSpryks:
  - AddClientInterface
  - AddClientFactory
