spryk: template
description: "Adds a new *Module*ClientInterface to the Client application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ClientInterface.php.twig

  targetFilename:
    value: "%module%ClientInterface.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Client/%module%/"

preSpryks:
  - AddClient
