spryk: template
description: "Adds a new *Module*ClientDependencyProvider to the Client application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ClientDependencyProvider.php.twig

  targetFilename:
    value: "%module%DependencyProvider.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Client/%module%/"

preSpryks:
  - CreateModule
