spryk: update-yml
description: "Updates the *module* test suite configuration."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedBusinessTestSuiteCodeceptionConfiguration.yml.twig

preSpryks:
  - AddCodeceptionConfiguration
