spryk: method
description: "Adds a new method to the *module*FacadeInterface."

arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  comment:
    multiline: true

  method: ~
  input: ~
  output: ~

  template:
    value: InterfaceMethod.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Business\\%module%FacadeInterface"

preSpryks:
  - AddZedBusinessFacadeInterface
