spryk: method
description: "Adds a new method to the *module* dependency facade bridge."

arguments:

  module: ~
  dependentModule: ~

  moduleOrganization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Method.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Dependency\\Facade\\%module%To%dependentModule%FacadeBridge"

preSpryks:
  - AddZedBusinessFacade
  - AddZedDependencyFacadeBridge

postSpryks:
  - AddZedDependencyFacadeInterfaceMethod
