spryk: template
description: "Adds a new Console command to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  className: ~

  consoleCommand: ~

  template:
    value: ZedConsole.php.twig

  targetFilename:
    value: "%className%Console.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Communication/Plugin/Console/"

preSpryks:
  - CreateModule

