spryk: structure
description: "Adds a new *module* Business test suite directory."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  targetPath:
    default: "%module%/"

  directories:
    value:
      - "tests/%moduleOrganization%Test/Zed/%module%/Business/"

postSpryks:
  - AddZedBusinessTestSuiteConfiguration
