spryk: method
description: "Adds a new test method to the *module*FacadeTest."

arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  method:
    callback:
      - ZedTestMethodNameCallback

  output:
    value: void

  template:
    value: Method.php.twig

  target:
    value: "%moduleOrganization%Test\\Zed\\%module%\\Business\\%module%FacadeTest"

preSpryks:
  - AddZedBusinessFacadeTest
