spryk: template
description: "Adds a new *module*RepositoryInterface to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedPersistenceRepositoryInterface.php.twig

  targetFilename:
    value: "%module%RepositoryInterface.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Persistence/"

preSpryks:
  - AddZedPersistenceRepository
