spryk: template
description: "Adds a new *module*QueryContainerInterface to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedQueryContainerInterface.php.twig

  targetFilename:
    value: "%module%QueryContainerInterface.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Persistence/"

preSpryks:
  - AddZedQueryContainer
