spryk: template
description: "Adds a new *module*FacadeTest."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedBusinessFacadeTest.php.twig

  targetFilename:
    value: "%module%FacadeTest.php"

  targetPath:
    default: "%module%/tests/%moduleOrganization%Test/Zed/%module%/Business/"

#preSpryks:
#  - AddZedBusinessTestSuite
