spryk: method
description: "Adds a new method to the Zed controller."

arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  controller:
    default: Index

  method:
    default: indexAction

  returnType:
    default: void

  template:
    value: MethodZedController.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Communication\\Controller\\%controller%Controller"

preSpryks:
  - AddZedController

postSpryks:
  - AddZedPresentationTwig
  - AddZedNavigationNode

