spryk: structure
description: "Creates a new *module* structure."
priority: 1

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  targetPath:
    default: "%module%/"

  directories:
    value:
      - src/

postSpryks:
  - AddReadme
  - AddComposerJson
  - AddLicense
  - AddContributing
  - AddChangelog
  - AddTravis
  - AddGitattributes
  - AddGitignore
  - AddPhpStanJson
  - AddPhpStanNeon
