spryk: template
description: "Adds a new *module*Facade to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessFacade.php.twig

  targetFilename:
    value: "{{ module }}Facade.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedBusinessFacadeInterface
  - AddZedBusinessFactory
