spryk: method
description: "Adds a new method to the *module*FacadeInterface."

arguments:

  module: ~

  organization:
    default: Spryker

  specification:
    multiline: true

  method:
    inherit: true

  input: ~
  output: ~

  annotations:
    value:
      - "@api"

  template:
    value: InterfaceMethod.php.twig

  target:
    value: "%organization%\\Zed\\%module%\\Business\\%module%FacadeInterface"

preSpryks:
  - AddZedBusinessFacadeInterface
