spryk: template
description: "Adds a new *module*BusinessFactory to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: ZedBusinessFactory.php.twig

  targetFilename:
    value: "%module%BusinessFactory.php"

  targetPath:
    default: "%module%/src/%organization%/Zed/%module%/Business/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedBusinessFacade
