spryk: update-yml
description: "Updates the *module* test configuration and adds the suite configuration for Business tests."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedBusinessTestSuiteCodeceptionConfiguration.yml.twig

  afterElement:
    value: coverage

  addToElement:
    value: suites

  targetPath:
    value: "%module%/tests/%moduleOrganization%Test/Zed/%module%/codeception.yml"

preSpryks:
  - AddZedTestCodeceptionConfiguration
