spryk: method
description: "Adds a method to the *moduleName* BusinessFactory."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  subDirectory:
    isOptional: true

  className: ~

  method:
    callbackOnly: true
    callback: ZedBusinessFactoryMethodNameCallback

  dependencyMethods:
    isMultiple: true
    isOptional: true

  template:
    value: Zed/Business/MethodBusinessFactory.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Business\\{{ moduleName }}BusinessFactory"

preSpryks:
  - AddZedBusinessFactory

