spryk: method
description: "Adds a new method to the *module*Facade."

arguments:

  module: ~

  organization:
    default: Spryker

  comment:
    multiline: true

  method: ~

  input:
    isOptional: true
    isMultiple: true

  output:
    isOptional: true

  annotations:
    value:
      - "{@inheritdoc}"
      - "@api"

  template:
    value: Method.php.twig

  target:
    value: "%organization%\\Zed\\%module%\\Business\\%module%Facade"

preSpryks:
  - AddZedBusinessFacade

postSpryks:
  - AddZedBusinessFacadeInterfaceMethod
  - AddZedBusinessFacadeMethodTest
