spryk: template
description: "Adds a new *moduleName*BusinessFactory to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessFactory.php.twig

  targetFilename:
    value: "{{ moduleName }}BusinessFactory.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Business/"

preSpryks:
  - AddSprykerModule

postSpryks:
  - AddZedBusinessFacade
  - AddZedDependencyProvider
  - AddZedConfig
