spryk: template
description: "Adds a new *moduleName*FacadeInterface to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessFacadeInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}FacadeInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Business/"

preSpryks:
  - AddZedBusinessFacade
