spryk: update-yml
description: "Updates the *moduleName* test configuration and adds the suite configuration for Business tests."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessTestSuiteCodeceptionConfiguration.yml.twig

  afterElement:
    value: coverage

  addToElement:
    value: suites

  targetPath:
    value: "{{ moduleName }}/tests/{{ organization }}Test/Zed/{{ moduleName }}/codeception.yml"

preSpryks:
  - AddZedTestCodeceptionConfiguration
