spryk: template
description: "Adds a new *moduleName*FacadeTest."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessFacadeTest.php.twig

  targetFilename:
    value: "{{ moduleName }}FacadeTest.php"

  targetPath:
    default: "{{ moduleName }}/tests/{{ organization }}Test/Zed/{{ moduleName }}/Business/"

preSpryks:
  - AddZedBusinessTestSuite
