spryk: method
description: "Adds a new method to the *module*Facade."

arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  comment:
    multiline: true

  method: ~
  input: ~
  output: ~

  annotations:
    value:
      - "{@inheritdoc}"
      - "@api"

  template:
    value: Method.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Business\\%module%Facade"

preSpryks:
  - AddZedBusinessFacade

postSpryks:
  - AddZedBusinessFacadeInterfaceMethod
  - AddZedBusinessFacadeMethodTest
