spryk: structure
description: "Adds a new *module* Business test suite directory."

arguments:
  module: ~

  organization:
    default: Spryker

  targetPath:
    default: "{{ module }}/"

  directories:
    value:
      - "tests/{{ organization }}Test/Zed/{{ module }}/Business/"

postSpryks:
  - AddZedBusinessTestSuiteConfiguration
