spryk: structure
description: "Adds a new *moduleName*Business test suite directory."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  targetPath:
    default: "{{ moduleName }}/"

  directories:
    value:
      - "tests/{{ organization }}Test/Zed/{{ moduleName }}/Business/"

postSpryks:
  - AddZedBusinessTestSuiteConfiguration
