spryk: method
description: "Adds a method to the *module*BusinessFactory."
mode: both

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  subDirectory:
    isOptional: true

  className: ~

  method:
    callbackOnly: true
    callback: ZedBusinessFactoryMethodNameCallback

  dependencyMethods:
    isMultiple: true
    isOptional: true

  template:
    value: Zed/Business/MethodBusinessFactory.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Business\\{{ module }}BusinessFactory"

preSpryks:
  - AddZedBusinessFactory

