spryk: method
description: "Adds a new method to the *moduleName*Facade."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  comment:
    multiline: true

  method: ~

  input:
    isOptional: true
    isMultiple: true

  output:
    isOptional: true

  annotations:
    value:
      - "{@inheritdoc}"
      - "@api"

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Business\\{{ moduleName }}Facade"

preSpryks:
  - AddZedBusinessFacade

postSpryks:
  - AddZedBusinessFacadeInterfaceMethod
  - AddZedBusinessFacadeMethodTest
