spryk: method
description: "Adds a new method to the *moduleName*FacadeInterface."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  specification:
    multiline: true

  method:
    inherit: true

  input:
    isOptional: true
    isMultiple: true

  output:
    isOptional: true

  annotations:
    value:
      - "@api"

  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Business\\{{ moduleName }}FacadeInterface"

preSpryks:
  - AddZedBusinessFacadeInterface
