spryk: template
description: "Adds a new *module*FacadeTest."
mode: both

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/Business/ZedBusinessFacadeTest.php.twig

  targetFilename:
    value: "{{ module }}FacadeTest.php"

  targetPath:
    default: "{{ module }}/tests/{{ organization }}Test/Zed/{{ module }}/Business/"

preSpryks:
  - AddZedBusinessTestSuite
