spryk: template
description: "Adds a new Abstract*tableName*Query class to Zed's persistence layer."

arguments:
  moduleName: ~
  targetModule: ~
  tableName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/Propel/AbstractQuery.php.twig

  targetFilename:
    value: "Abstract{{ tableName | camelCased }}Query.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/Propel/"

preSpryks:
  - AddZedPersistencePropelSchemaTable

postSpryks:
  - AddZedPersistencePropelAbstractEntity
