spryk: template
description: "Adds a new Abstract*tableName* class to Zed's persistence layer."

arguments:
  module: ~
  targetModule: ~
  tableName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/Propel/AbstractEntity.php.twig

  targetFilename:
    value: "Abstract{{ tableName | camelCased }}.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Persistence/Propel/"

preSpryks:
  - AddZedPersistencePropelSchemaTable

postSpryks:
  - AddZedPersistencePropelAbstractQuery
