spryk: schema
description: "Adds a new table to the spy_*targetModule*.schema.xml."

arguments:
  moduleName: ~
  targetModule: ~
  tableName: ~

  organization:
    default: Spryker

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/Propel/Schema/spy_{{ targetModule | underscored }}.schema.xml"

preSpryks:
  - AddZedPersistencePropelSchema


postSpryks:
  - AddZedPersistencePropelAbstractEntity
  - AddZedPersistencePropelAbstractQuery
