spryk: template
description: "Adds a new spy_*targetModule*.schema.xml to the Zed application."

arguments:
  moduleName: ~
  targetModule: ~
  tableName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/Propel/Schema/schema.xml.twig

  targetFilename:
    value: "spy_{{ targetModule | underscored }}.schema.xml"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/Propel/Schema/"

preSpryks:
  - CreateSprykerModule
