spryk: template
description: "Adds a new *moduleName*DependencyProvider to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/ZedDependencyProvider.php.twig

  targetFilename:
    value: "{{ moduleName }}DependencyProvider.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
