spryk: template
description: "Adds a new *module*Config to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/ZedConfig.php.twig

  targetFilename:
    value: "{{ module }}Config.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/"

preSpryks:
  - AddSprykerModule
