spryk: update-yml
description: "Adds the include for the Zed test suite to the codeception.yml."

arguments:
  module: ~

  organization:
    default: Spryker

  afterElement:
    value: actor

  addToElement:
    value: include

  content:
    value: "tests/{{ organization }}Test/Zed/{{ module }}"

  targetPath:
    value: "{{ module }}/codeception.yml"

preSpryks:
  - AddSprykerCodeceptionConfiguration
