spryk: template
description: "Adds a new *moduleName*Config to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/ZedConfig.php.twig

  targetFilename:
    value: "{{ moduleName }}Config.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
