spryk: template
description: "Add the Zed *moduleName* test suite configuration without any suite."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/ZedTestCodeceptionConfiguration.yml.twig

  targetPath:
    value: "{{ moduleName }}/tests/SprykerTest/Zed/{{ moduleName }}/"

  targetFilename:
    value: codeception.yml

preSpryks:
  - AddSprykerCodeceptionConfiguration

postSpryks:
  - AddZedTestSuiteToCodeceptionConfiguration
