spryk: template
description: "Add the Zed *module* test suite configuration without any suite."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ZedTestCodeceptionConfiguration.yml.twig

  targetPath:
    value: "%module%/tests/SprykerTest/Zed/%module%/"

  targetFilename:
    value: codeception.yml

preSpryks:
  - AddSprykerCodeceptionConfiguration

postSpryks:
  - AddZedTestSuiteToCodeceptionConfiguration
