spryk: template
description: "Adds a new *module*DependencyProvider to the Zed application."
mode: both

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/ZedDependencyProvider.php.twig

  targetFilename:
    value: "{{ module }}DependencyProvider.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/"

preSpryks:
  - AddModule
