spryk: update-yml
description: "Adds the include for the Zed test suite to the codeception.yml."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  afterElement:
    value: actor

  addToElement:
    value: include

  content:
    value: "tests/SprykerTest/Zed/{{ moduleName }}"

  targetPath:
    value: "{{ moduleName }}/codeception.yml"

preSpryks:
  - AddSprykerCodeceptionConfiguration
