spryk: template
description: "Add the Zed *module* test suite configuration without any suite."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/ZedTestCodeceptionConfiguration.yml.twig

  targetPath:
    value: "{{ module }}/tests/SprykerTest/Zed/{{ module }}/"

  targetFilename:
    value: codeception.yml

preSpryks:
  - AddSprykerCodeceptionConfiguration

postSpryks:
  - AddZedTestSuiteToCodeceptionConfiguration
