spryk: template
description: "Adds a new *moduleName*To*dependentModule*ClientBridge."

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  organization:
    default: Spryker

  dependentModule:
    moduleFilter:
      application: Client

  dependentModuleOrganization:
    default: Spryker


  template:
    value: Zed/Dependency/Client/ZedDependencyClientBridge.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}ClientBridge.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Dependency/Client/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedDependencyClientInterface
  - AddZedDependencyClientBusinessFactoryMethod
  - AddZedDependencyClientDependencyProviderMethod
  - AddZedDependencyClientDependencyProviderConstant:
      arguments:
          name:
            value: "CLIENT_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} client"
          visibility:
            value:  "public"
