spryk: template
description: "Adds a new *moduleName* To*dependentModule*ClientInterface."

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  dependentModule:
    moduleFilter:
      application: Client

  organization:
    default: Spryker

  template:
    value: Zed/Dependency/Client/ZedDependencyClientInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}ClientInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Dependency/Client/"

preSpryks:
  - AddZedDependencyClientBridge
