spryk: constant
description: "Adds a Client dependency constant to the *module*DependencyProvider."
mode: both

arguments:
  module:
    moduleFilter:
      application: Zed

  dependentModule:
    moduleFilter:
      application: Client

  organization:
    default: Spryker

  name: ~
  value: ~
  visibility:
    value: "public"

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\{{ module }}DependencyProvider"

preSpryks:
  - AddZedDependencyProvider

