spryk: template
description: "Adds a new *module*To*dependentModule*ClientInterface."

arguments:
  module:
    moduleFilter:
      application: Zed

  dependentModule:
    moduleFilter:
      application: Client

  organization:
    default: Spryker

  template:
    value: Zed/Dependency/Client/ZedDependencyClientInterface.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ClientInterface.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Dependency/Client/"

preSpryks:
  - AddZedDependencyClientBridge
