spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency Client bridge."
priority: 1

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  organization:
    default: Spryker

  dependentModule:
    moduleFilter:
      application: Client

  methods:
    type: MethodNameChoice
    choiceLoader: ClientMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - moduleName
      - choiceLoader

  template:
    value: Zed/Dependency/ZedDependencyBridgeMethod.php.twig

  dependencyType:
    value: Client

  sourceClass:
    value: "{{ organization }}\\Client\\{{ dependentModule }}\\{{ dependentModule }}Client"

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Dependency\\Client\\{{ moduleName }}To{{ dependentModule }}ClientBridge"

preSpryks:
  - AddZedDependencyClientBridge

postSpryks:
  - AddZedDependencyClientBridgeInterfaceMethod
