spryk: template
description: "Adds a new Glue storefront resource."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Glue/Storefront/GlueStorefrontResource.php.twig

  targetFilename:
    value: "{{ module }}Resource.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
  - AddGlueResourceInterface

postSpryks:
  - AddGlueStorefrontFactory
  - AddGlueStorefrontDependencyProvider
  - AddSharedTransferSchema
  - AddGlueConfig
