spryk: template
description: "Adds a new Glue storefront rest resource relationship plugin."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  pluginName: ~

  template:
    value: Glue/Storefront/GlueStorefrontRestResourceRelationshipPlugin.php.twig

  targetFilename:
    value: "{{ pluginName }}.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/Plugin/GlueStorefront"

preSpryks:
  - AddGlueStorefrontResource
