spryk: template
description: "Adds a new Glue Storefront factory"
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Glue/Storefront/GlueStorefrontFactory.php.twig

  targetFilename:
    value: "{{ module }}Factory.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}"

preSpryks:
  - AddModule
