spryk: template
description: "Adds a new twig file to the *moduleName* Presentation layer."

config:
  noRender: true

arguments:

  moduleName: ~

  organization:
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - RemoveControllerSuffixCallback

  method:
    callback:
      - RemoveActionSuffixCallback

  template:
    value: Zed/Presentation/ZedPresentationTwig.twig

  targetFilename:
    value: "{{ method | removeActionSuffix | dasherize | lcfirst }}.twig"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Presentation/{{ controller | classNameShort | removeControllerSuffix }}/"

preSpryks:
  - AddZedCommunicationControllerAction
