spryk: template
description: "Adds a new CONTRIBUTING.md to the Modules root."
mode: core

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: CONTRIBUTING.md.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - AddModule
