spryk: template
description: "Adds a new .travis.yml to the Modules root."
mode: core

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: travis.yml.twig

  targetFilename:
    value: .travis.yml

  targetPath:
    value: "{{ module }}/"

preSpryks:
  - AddModule
