spryk: template
description: "Adds a new tooling.yml to the Modules root."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: tooling.yml.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - AddModule
