spryk: template
description: "Adds a new phpstan.neon to the Modules root."
mode: core

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: phpstan.neon.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - AddModule
