spryk: template
description: "Adds a new .coveralls.yml to the Modules root."
mode: core

arguments:
  module: ~

  organization:
    default: Spryker

  repositoryToken: ~

  template:
    value: coveralls.yml.twig

  targetFilename:
      value: .coveralls.yml

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - AddModule
