spryk: template
description: "Adds a new .scrutinizer.yml to the Modules root."
mode: core

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: scrutinizer.yml.twig

  targetFilename:
    value: .scrutinizer.yml

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - AddModule
