spryk: structure
description: "Adds a new *module* structure."
priority: 1
mode: both

arguments:
  module:
    inherit: true
    type: NewModuleType

  organization:
    inherit: true
    default: Spryker

  targetPath:
    value: "{{ module }}/"

  directories:
    value:
      - "src/{{ organization }}/"

postSpryks:
  - AddModuleReadme
  - AddModuleComposerJson
  - AddModuleLicense
  - AddModuleContributing
  - AddModuleChangelog
  - AddModuleCi
  - AddModuleGitattributes
  - AddModuleGitignore
  - AddModuleTooling
  - AddModulePhpStanJson
  - AddModulePhpStanNeon
