spryk: template
description: "Adds a new CHANGELOG.md to the Modules root."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: CHANGELOG.md.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - CreateSprykerModule
