spryk: template
description: "Adds a new .travis.yml to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: travis.yml.twig

  targetFilename:
    value: .travis.yml

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule
