spryk: template
description: "Adds a new .gitignore to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: gitignore.twig

  targetFilename:
    value: .gitignore

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule
