spryk: template
description: "Adds a new CONTRIBUTING.md to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: CONTRIBUTING.md.twig

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule
