spryk: template
description: "Adds a new .scrutinizer.yml to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: scrutinizer.yml.twig

  targetFilename:
    value: .scrutinizer.yml

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
