spryk: template
description: "Adds a new tooling.yml to the Modules root."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: tooling.yml.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - CreateSprykerModule
