spryk: template
description: "Adds a new CHANGELOG.md to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: CHANGELOG.md.twig

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
