spryk: template
description: "Adds a new phpstan.neon to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: phpstan.neon.twig

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule
