spryk: template
description: "Adds a new .gitattributes to the Modules root."

arguments:
  module: ~

  template:
    value: gitattributes.twig

  targetFilename:
    value: .gitattributes

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - CreateSprykerModule
