spryk: template
description: "Adds a new codeception.yml to the Modules root."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: codeception.yml.twig

  targetPath:
    default: "%module%/"

preSpryks:
  - CreateSprykerModule
