spryk: template
description: "Adds a new LICENSE to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: LICENSE.twig

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
