spryk: template
description: "Adds a new codeception.yml to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: codeception.yml.twig

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
