spryk: template
description: "Adds a new LICENSE to the Modules root."

arguments:
  module: ~

  template:
    value: LICENSE.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - CreateSprykerModule
