spryk: template
description: "Adds a new .coveralls.yml to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  repositoryToken: ~

  template:
    value: coveralls.yml.twig

  targetFilename:
      value: .coveralls.yml

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule
