spryk: template
description: "Adds a new .gitattributes to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: gitattributes.twig

  targetFilename:
    value: .gitattributes

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
