spryk: template
description: "Adds a new phpstan.json to the Modules root."

arguments:
  module: ~

  template:
    value: phpstan.json.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - CreateSprykerModule
