spryk: template
description: "Adds a new composer.json to the Modules root."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: composer.json.twig

  targetPath:
    default: "{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
