spryk: template
description: "Adds a new CONTRIBUTING.md to the Modules root."

arguments:
  module: ~

  template:
    value: CONTRIBUTING.md.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - CreateSprykerModule
