spryk: template
description: "Adds a new README.md to the Modules root."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: README.md.twig

  targetPath:
    default: "{{ module }}/"

preSpryks:
  - CreateSprykerModule
