spryk: structure
description: "Creates a new *module* structure."
priority: 1

arguments:
  module:
    type: NewModuleType

  organization:
    default: Spryker

  targetPath:
    default: "{{ module }}/"

  directories:
    value:
      - "src/{{ organization }}/"

postSpryks:
  - AddSprykerReadme
  - AddSprykerComposerJson
  - AddSprykerLicense
  - AddSprykerContributing
  - AddSprykerChangelog
  - AddSprykerTravis
  - AddSprykerGitattributes
  - AddSprykerGitignore
  - AddSprykerPhpStanJson
  - AddSprykerPhpStanNeon
