spryk: template
description: "Adds a new Glue back office resource."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Glue/BackOffice/GlueBackOfficeResource.php.twig

  targetFilename:
    value: "{{ module }}Resource.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}"

preSpryks:
  - AddGlueResourceInterface

postSpryks:
  - AddGlueBackOfficeFactory
  - AddGlueBackOfficeDependencyProvider
  - AddSharedTransferSchema
  - AddGlueConfig
