spryk: template
description: "Adds a new Glue back office *module*DependencyProvider"
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Glue/BackOffice/GlueBackOfficeDependencyProvider.php.twig

  targetFilename:
    value: "{{ module }}DependencyProvider.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Glue/{{ module }}/"

preSpryks:
  - AddModule
