spryk: method
description: "Adds a new method to the *target* business model."

application: Zed
layer: Business

priority: 1

arguments:

  module: ~

  organization:
    default: Spryker

  className: ~

  method: ~

  input:
    type: ZedBusinessModel
    isOptional: true
    isMultiple: true

  output:
    isOptional: true

  facadeMethod:
    default: "%method%"

  template:
    value: Method.php.twig

  target:
    value: "%className%"

preSpryks:
  - AddZedBusinessModel:
      arguments:
        subDirectory:
          callback: ZedBusinessModelSubDirectoryCallback

        className:
          callback: ClassNameShortCallback

postSpryks:
  - AddZedBusinessModelInterfaceMethod
  - AddZedBusinessFacadeMethod:
      isOptional: true
      arguments:
        method:
          value: "%facadeMethod%"
