spryk: template
description: "Adds a new Business model interface to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  subDirectory:
    isOptional: true

  className: ~

  interfaceName:
    default: "{{ className }}Interface"

  template:
    value: Zed/Business/Model/ZedBusinessModelInterface.php.twig

  targetFilename:
    callbackOnly: true
    callback: ZedBusinessModelInterfaceTargetFilenameCallback

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Business/"

preSpryks:
  - AddSprykerModule
  - AddZedBusinessModel:
      arguments:
        subDirectory:
          callback: ZedBusinessModelSubDirectoryCallback

        className:
          callback: ClassNameShortCallback
