spryk: method
description: "Adds a new method to the *target* business model interface."

arguments:

  module: ~

  organization:
    default: Spryker

  className: ~

  method: ~
  input: ~
  output: ~

  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: "{{ className }}Interface"

preSpryks:
  - AddZedBusinessModel:
      arguments:
        subDirectory:
          callback: ZedBusinessModelSubDirectoryCallback

        className:
          callback: ClassNameShortCallback

postSpryks:
  - AddZedBusinessModelMethod
