spryk: template
description: "Adds a new Business model to the Zed application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  subDirectory:
    isOptional: true

  className: ~

  constructorArguments:
    type: ZedBusinessDependency
    isOptional: true

  interfaceName:
    default: "%className%Interface"

  template:
    value: ZedBusinessModel.php.twig

  targetFilename:
    callbackOnly: true
    callback: ZedBusinessModelTargetFilenameCallback

  targetPath:
    default: "%module%/src/%moduleOrganization%/Zed/%module%/Business/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedBusinessModelInterface
  - AddZedBusinessFactoryMethod

