spryk: template
description: "Adds a new Business model to the Zed application."
mode: both

application: Zed
layer: Business

priority: 1

arguments:
  module: ~

  organization:
    default: Spryker

  subDirectory:
    isOptional: true

  className: ~

  constructorArguments:
    type: ZedBusinessDependency
    typeOptions:
        - module
        - spryk
    isOptional: true
    isMultiple: true

  interfaceName:
    default: "{{ className }}Interface"

  template:
    value: Zed/Business/Model/ZedBusinessModel.php.twig

  targetFilename:
    callbackOnly: true
    callback: ZedBusinessModelTargetFilenameCallback

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedBusinessModelInterface
  - AddZedBusinessFactoryMethod

