spryk: template
description: "Adds a new Controller to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  controller:
    callback: ControllerNameCallback

  template:
    value: Zed/Communication/ZedCommunicationController.php.twig

  targetFilename:
    value: "{{ controller | controllerName }}Controller.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Communication/Controller/"

preSpryks:
  - CreateSprykerModule

