spryk: method
description: "Adds a new method to the Zed controller."

arguments:

  module: ~

  organization:
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - ControllerNameCallback
    type: ClassNameChoice
    choiceLoader: ZedCommunicationControllerChoiceLoader
    typeOptions:
      - module
      - spryk
      - choiceLoader

  method:
    callback: ActionNameCallback

  output:
    default: void

  template:
    value: Zed/Communication/MethodZedCommunicationController.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Communication\\Controller\\{{ controller | classNameShort | controllerName }}Controller"

preSpryks:
  - AddZedCommunicationController

postSpryks:
  - AddZedPresentationTwig
  - AddZedNavigationNode

