spryk: navigation
description: "Adds a new navigation node entry tho the *moduleName* navigation.xml."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - RemoveControllerSuffixCallback

  method:
    callback:
      - RemoveActionSuffixCallback

  targetPath:
    value: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Communication/navigation.xml"

preSpryks:
  - AddZedNavigationSchema
