spryk: template
description: "Adds a new navigation.xml to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/Communication/navigation.xml.twig

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Communication/"

preSpryks:
  - CreateSprykerModule
