spryk: navigation
description: "Adds a new navigation node entry tho the *module* navigation.xml."
mode: both

arguments:
  module: ~

  organization:
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - RemoveControllerSuffixCallback

  method:
    callback:
      - RemoveActionSuffixCallback

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Communication/navigation.xml"

preSpryks:
  - AddZedNavigationSchema
