spryk: template
description: "Adds a new navigation.xml to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Communication/navigation.xml.twig

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Communication/"

preSpryks:
  - CreateSprykerModule
