spryk: template
description: "Adds a new Console command to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  className: ~

  consoleCommand: ~

  template:
    value: Zed/Communication/ZedCommunicationConsole.php.twig

  targetFilename:
    value: "{{ className }}Console.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Communication/Console/"

preSpryks:
  - AddModule

