spryk: template
description: "Adds a new *moduleName* CommunicationFactory to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Communication/ZedCommunicationFactory.php.twig

  targetFilename:
    value: "{{ moduleName }}CommunicationFactory.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Communication/"

preSpryks:
  - CreateSprykerModule
