spryk: template
description: "Adds a new *module*CommunicationFactory to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/Communication/ZedCommunicationFactory.php.twig

  targetFilename:
    value: "{{ module }}CommunicationFactory.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Communication/"

preSpryks:
  - AddModule
