spryk: template
description: "Adds a new Controller to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  controller:
    default: Index

  template:
    value: ZedCommunicationController.php.twig

  targetFilename:
    value: "{{ controller }}Controller.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Communication/Controller/"

preSpryks:
  - CreateSprykerModule

