spryk: method
description: "Adds a new method to the *module* dependency facade bridge."

arguments:

  module: ~
  dependentModule: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: InterfaceMethod.php.twig

  target:
    value: "%organization%\\Zed\\%module%\\Dependency\\Facade\\%module%To%dependentModule%FacadeInterface"

preSpryks:
  - AddZedDependencyFacadeInterface
