spryk: method
description: "Adds a new method to the *module* dependency facade bridge."

arguments:

  module: ~
  dependentModule: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Dependency\\Facade\\{{ module }}To{{ dependentModule }}FacadeBridge"

preSpryks:
  - AddZedBusinessFacade
  - AddZedDependencyFacadeBridge

postSpryks:
  - AddZedDependencyFacadeInterfaceMethod
