spryk: template
description: "Adds a new *module*To*dependentModule*FacadeBridge."

arguments:
  module: ~
  dependentModule: ~

  organization:
    default: Spryker

  template:
    value: ZedDependencyFacadeBridge.php.twig

  targetFilename:
    value: "%module%To%dependentModule%FacadeBridge.php"

  targetPath:
    default: "%module%/src/%organization%/Zed/%module%/Dependency/Facade/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedDependencyFacadeInterface
