spryk: method
description: "Adds a new action to the Zed controller."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - EnsureControllerSuffixCallback
    type: ClassNameChoice
    choiceLoader: ZedCommunicationControllerChoiceLoader
    typeOptions:
      - moduleName
      - spryk
      - choiceLoader

  method:
    callback: EnsureActionSuffixCallback

  output:
    default: void

  template:
    value: Zed/Communication/MethodZedCommunicationController.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Communication\\Controller\\{{ controller | classNameShort | ensureControllerSuffix }}"

preSpryks:
  - AddZedCommunicationController

postSpryks:
  - AddZedPresentationTwig
  - AddZedNavigationNode

