spryk: template
description: "Adds a new Controller to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - EnsureControllerSuffixCallback

  template:
    value: Zed/Communication/ZedCommunicationController.php.twig

  targetFilename:
    value: "{{ controller | classNameShort | ensureControllerSuffix }}.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Communication/Controller/"

preSpryks:
  - AddSprykerModule

