spryk: method
description: "Adds a new method to the *module*Repository."

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Persistence\\{{ module }}Repository"

preSpryks:
  - AddZedPersistenceRepository

postSpryks:
  - AddZedPersistenceRepositoryInterfaceMethod
