spryk: template
description: "Adds a new *moduleName* RepositoryInterface to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceRepositoryInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}RepositoryInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/"

preSpryks:
  - AddZedPersistenceRepository
