spryk: template
description: "Adds a new *moduleName*PersistenceFactory to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceFactory.php.twig

  targetFilename:
    value: "{{ moduleName }}PersistenceFactory.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/"

preSpryks:
  - CreateSprykerModule

