spryk: template
description: "Adds a new *module*EntityManager to the Zed application."
mode: both

arguments:
  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceEntityManager.php.twig

  targetFilename:
    value: "{{ module }}EntityManager.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedPersistenceFactory
  - AddZedPersistenceEntityManagerInterface
