spryk: method
description: "Adds a new method to the *module*Repository."

arguments:

  module: ~

  moduleOrganization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Method.php.twig

  target:
    value: "%moduleOrganization%\\Zed\\%module%\\Persistence\\%module%Repository"

preSpryks:
  - AddZedPersistenceRepository

postSpryks:
  - AddZedPersistenceRepositoryInterfaceMethod
