spryk: template
description: "Adds a new *module*Repository to the Zed application."
mode: both

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceRepository.php.twig

  targetFilename:
    value: "{{ module }}Repository.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - AddModule

postSpryks:
  - AddZedPersistenceFactory
  - AddZedPersistenceRepositoryInterface

