spryk: method
description: "Adds a new method to the *moduleName*EntityManagerInterface."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Persistence\\{{ moduleName }}EntityManagerInterface"

preSpryks:
  - AddZedPersistenceEntityManagerInterface
