spryk: template
description: "Adds a new *moduleName*EntityManager to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceEntityManager.php.twig

  targetFilename:
    value: "{{ moduleName }}EntityManager.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/"

preSpryks:
  - AddSprykerModule

postSpryks:
  - AddZedPersistenceFactory
  - AddZedPersistenceEntityManagerInterface
