spryk: template
description: "Adds a new *module*RepositoryInterface to the Zed application."
mode: both

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceRepositoryInterface.php.twig

  targetFilename:
    value: "{{ module }}RepositoryInterface.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - AddZedPersistenceRepository
