spryk: template
description: "Adds a new *moduleName* EntityManagerInterface to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceEntityManagerInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}EntityManagerInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/"

preSpryks:
  - AddZedPersistenceEntityManager

