spryk: method
description: "Adds a new method to the *module*EntityManagerInterface."

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: InterfaceMethod.php.twig

  target:
    value: "%organization%\\Zed\\%module%\\Persistence\\%module%EntityManagerInterface"

preSpryks:
  - AddZedPersistenceEntityManagerInterface
