spryk: template
description: "Adds a new *moduleName* Repository to the Zed application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Zed/Persistence/ZedPersistenceRepository.php.twig

  targetFilename:
    value: "{{ moduleName }}Repository.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Persistence/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedPersistenceFactory
  - AddZedPersistenceRepositoryInterface

