spryk: template
description: "Adds a new *module*EntityManagerInterface to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: ZedPersistenceEntityManagerInterface.php.twig

  targetFilename:
    value: "{{ module }}EntityManagerInterface.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - AddZedPersistenceEntityManager

