spryk: method
description: "Adds a new method to the *moduleName*Repository."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Persistence\\{{ moduleName }}Repository"

preSpryks:
  - AddZedPersistenceRepository

postSpryks:
  - AddZedPersistenceRepositoryInterfaceMethod
