spryk: method
description: "Adds a new method to the *module*EntityManager."
mode: both

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Persistence\\{{ module }}EntityManager"

preSpryks:
  - AddZedPersistenceEntityManager

postSpryks:
  - AddZedPersistenceEntityManagerInterfaceMethod
