spryk: method
description: "Adds a new method to the *moduleName*EntityManager."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Persistence\\{{ moduleName }}EntityManager"

preSpryks:
  - AddZedPersistenceEntityManager

postSpryks:
  - AddZedPersistenceEntityManagerInterfaceMethod
