spryk: method
description: "Adds a new method to the *module*RepositoryInterface."
mode: both

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: "{{ organization }}\\Zed\\{{ module }}\\Persistence\\{{ module }}RepositoryInterface"

preSpryks:
  - AddZedPersistenceRepositoryInterface
