spryk: template
description: "Adds a new *module*EntityManager to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: ZedPersistenceEntityManager.php.twig

  targetFilename:
    value: "{{ module }}EntityManager.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddZedPersistenceFactory
  - AddZedPersistenceEntityManagerInterface
