spryk: template
description: "Adds a new *module*PersistenceFactory to the Zed application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: ZedPersistenceFactory.php.twig

  targetFilename:
    value: "{{ module }}PersistenceFactory.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Persistence/"

preSpryks:
  - CreateSprykerModule

