spryk: method
description: "Adds a new method to the *module*EntityManager."

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Method.php.twig

  target:
    value: "%organization%\\Zed\\%module%\\Persistence\\%module%EntityManager"

preSpryks:
  - AddZedPersistenceEntityManager

postSpryks:
  - AddZedPersistenceEntityManagerInterfaceMethod
