spryk: template
description: "Adds a new *module*To*dependentModule*ServiceInterface."

arguments:
  module:
    moduleFilter:
      application: Zed

  dependentModule:
    moduleFilter:
      application: Service

  organization:
    default: Spryker

  template:
    value: Zed/Dependency/Service/ZedDependencyServiceInterface.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ServiceInterface.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Zed/{{ module }}/Dependency/Service/"

preSpryks:
  - AddZedDependencyServiceBridge
