spryk: template
description: "Adds a new *moduleName*To*dependentModule*ServiceInterface."

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  dependentModule:
    moduleFilter:
      application: Service

  organization:
    default: Spryker

  template:
    value: Zed/Dependency/Service/ZedDependencyServiceInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}ServiceInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Zed/{{ moduleName }}/Dependency/Service/"

preSpryks:
  - AddZedDependencyServiceBridge
