spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency Service bridge interface."

arguments:
  moduleName:
    moduleFilter:
      application: Zed

  organization:
    default: Spryker

  dependentModule:
    moduleFilter:
      application: Service

  methods:
    type: MethodNameChoice
    choiceLoader: ServiceMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - moduleName
      - choiceLoader

  template:
    value: Zed/Dependency/ZedDependencyBridgeInterfaceMethod.php.twig

  dependencyType:
    value: Service

  sourceClass:
    value: "{{ organization }}\\Service\\{{ dependentModule }}\\{{ dependentModule }}ServiceInterface"

  target:
    value: "{{ organization }}\\Zed\\{{ moduleName }}\\Dependency\\Service\\{{ moduleName }}To{{ dependentModule }}ServiceInterface"

preSpryks:
  - AddZedDependencyServiceInterface

postSpryks:
  - AddZedDependencyServiceBridgeMethod


