spryk: method
description: "Adds a new Interface method to the *Module*ClientInterface."

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  specification:
    multiline: true

  template:
    value: InterfaceMethod.php.twig

  target:
    value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}ClientInterface"

preSpryks:
  - AddClientInterface
