spryk: method
description: "Adds a new method to the *Module*Client."
priority: 1

arguments:

  module: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Client\\{{ module }}\\{{ module }}Client"

preSpryks:
  - AddClient

postSpryks:
  - AddClientInterfaceMethod
