spryk: template
description: "Adds a new *Module*Client to the Client application."
priority: 1

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Client/Client.php.twig

  targetFilename:
    value: "{{ moduleName }}Client.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Client/{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddClientDependencyProvider
  - AddClientInterface
  - AddClientFactory
