spryk: template
description: "Adds a new *Module*Client to the Client application."
priority: 1
mode: both

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Client/Client.php.twig

  targetFilename:
    value: "{{ module }}Client.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Client/{{ module }}/"

preSpryks:
  - AddModule

postSpryks:
  - AddClientDependencyProvider
  - AddClientInterface
  - AddClientFactory
