spryk: template
description: "Adds a new *module*Config to the Client application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Client/ClientConfig.php.twig

  targetFilename:
    value: "{{ module }}Config.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Client/{{ module }}/"

preSpryks:
  - AddModule
