spryk: template
description: "Adds a new *moduleName*Config to the Client application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Client/ClientConfig.php.twig

  targetFilename:
    value: "{{ moduleName }}Config.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Client/{{ moduleName }}/"

preSpryks:
  - AddSprykerModule
