spryk: template
description: "Adds a new *moduleName*ClientInterface to the Client application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Client/ClientInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}ClientInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Client/{{ moduleName }}/"

preSpryks:
  - AddClient
