spryk: template
description: "Adds a new *Module*ClientFactory to the Client application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: ClientFactory.php.twig

  targetFilename:
    value: "%module%Factory.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Client/%module%/"

preSpryks:
  - CreateSprykerModule

