spryk: method
description: "Adds a new Interface method to the *Module*ClientInterface."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  method: ~
  input: ~
  output: ~

  specification:
    multiline: true

  template:
    value: Common/InterfaceMethod.php.twig

  target:
    value: "{{ organization }}\\Client\\{{ moduleName }}\\{{ moduleName }}ClientInterface"

preSpryks:
  - AddClientInterface
