spryk: method
description: "Adds a new method to the Client *moduleName*Config."

arguments:

  moduleName: ~

  organization:
    default: Spryker

  comment:
    multiline: true
    isOptional: true

  method: ~
  input: ~
  output: ~

  template:
    value: Common/Method.php.twig

  target:
    value: "{{ organization }}\\Client\\{{ moduleName }}\\{{ moduleName }}Config"

preSpryks:
  - AddClientConfig

