spryk: template
description: "Adds a new *Module*ClientFactory to the Client application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Client/ClientFactory.php.twig

  targetFilename:
    value: "{{ moduleName }}Factory.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Client/{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule

