spryk: template
description: "Adds a new *module*ConstantsInterface to the shared application."

arguments:
  module: ~

  moduleOrganization:
    default: Spryker

  template:
    value: SharedConstantsInterface.php.twig

  targetFilename:
    value: "%module%Constants.php"

  targetPath:
    default: "%module%/src/%moduleOrganization%/Shared/%module%/"

preSpryks:
  - CreateSprykerModule
