spryk: template
description: "Adds a new *module*ConstantsInterface to the Shared application."
mode: both

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: Shared/SharedConstantsInterface.php.twig

  targetFilename:
    value: "{{ module }}Constants.php"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Shared/{{ module }}/"

preSpryks:
  - AddModule
