spryk: template
description: "Adds a new *moduleName*.transfer.xml to the Shared application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Shared/transfer.xml.twig

  targetFilename:
    value: "{{ moduleName | underscored }}.transfer.xml"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Shared/{{ moduleName }}/Transfer/"

preSpryks:
  - CreateSprykerModule
