spryk: template
description: "Adds a new *module*.schema.xml to the shared application."

arguments:
  module: ~

  organization:
    default: Spryker

  template:
    value: transfer.xml.twig

  targetFilename:
    value: "{{ module }}.transfer.xml"

  targetPath:
    default: "{{ module }}/src/{{ organization }}/Shared/{{ module }}/Transfer/"

preSpryks:
  - CreateSprykerModule
