spryk: template
description: "Adds a new *moduleName* ConstantsInterface to the Shared application."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  template:
    value: Shared/SharedConstantsInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}Constants.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Shared/{{ moduleName }}/"

preSpryks:
  - CreateSprykerModule
