spryk: constant
description: "Adds a Service dependency constant to the *moduleName* DependencyProvider."

arguments:

  moduleName: ~
  dependentModule: ~

  organization:
    default: Spryker

  name: ~
  value: ~
  visibility:
    value: "public"

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\{{ moduleName }}DependencyProvider"

preSpryks:
  - AddYvesDependencyProvider

