spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency Service bridge."
priority: 1

arguments:

  moduleName: ~
  organization:
    default: Spryker

  dependentModule: ~

  methods:
    type: MethodNameChoice
    choiceLoader: ServiceMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - module
      - choiceLoader

  template:
    value: Yves/Dependency/YvesDependencyBridgeMethod.php.twig

  dependencyType:
    value: Service

  sourceClass:
    value: "{{ organization }}\\Service\\{{ dependentModule }}\\{{ dependentModule }}Service"

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\Dependency\\Service\\{{ moduleName }}To{{ dependentModule }}ServiceBridge"

preSpryks:
  - AddYvesDependencyServiceBridge

postSpryks:
  - AddYvesDependencyServiceBridgeInterfaceMethod
