spryk: method
description: "Adds a Service dependency method to the *moduleName* Factory."

arguments:

  moduleName: ~
  dependentModule: ~

  organization:
    default: Spryker

  method:
    value: "get{{ dependentModule }}Service"

  template:
    value: Yves/Dependency/Service/YvesDependencyServiceFactoryMethod.php.twig

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\{{ moduleName }}Factory"

preSpryks:
  - AddYvesFactory

postSpryks:
  - AddYvesDependencyServiceDependencyProviderConstant:
      arguments:
        name:
          value: "SERVICE_{{ dependentModule | underscored | upper }}"
        value:
          value:  "{{ dependentModule | camelCaseToWhitespace | lower }} service"
        visibility:
          value:  "public"
