spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency Service bridge interface."

arguments:

  moduleName: ~
  organization:
    default: Spryker

  dependentModule: ~

  methods:
    type: MethodNameChoice
    choiceLoader: ServiceMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - module
      - choiceLoader

  template:
    value: Yves/Dependency/YvesDependencyBridgeInterfaceMethod.php.twig

  dependencyType:
    value: Service

  sourceClass:
    value: "{{ organization }}\\Service\\{{ dependentModule }}\\{{ dependentModule }}ServiceInterface"

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\Dependency\\Service\\{{ moduleName }}To{{ dependentModule }}ServiceInterface"

preSpryks:
  - AddYvesDependencyServiceInterface

postSpryks:
  - AddYvesDependencyServiceBridgeMethod
