spryk: template
description: "Adds a new *moduleName*To*dependentModule*ServiceBridge."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  dependentModule: ~

  dependentModuleOrganization:
    default: Spryker


  template:
    value: Yves/Dependency/Service/YvesDependencyServiceBridge.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}ServiceBridge.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Yves/{{ moduleName }}/Dependency/Service/"

preSpryks:
  - CreateSprykerModule

postSpryks:
  - AddYvesDependencyServiceInterface
  - AddYvesDependencyServiceFactoryMethod
  - AddYvesDependencyServiceDependencyProviderMethod
  - AddYvesDependencyServiceDependencyProviderConstant:
      arguments:
          name:
            value: "SERVICE_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} service"
          visibility:
            value:  "public"
