spryk: method
description: "Adds a Service dependency method to the *moduleName* DependencyProvider."

arguments:

  moduleName: ~
  dependentModule: ~

  organization:
    default: Spryker

  method:
    value: "add{{ dependentModule }}Service"

  template:
    value: Yves/Dependency/Service/YvesDependencyServiceDependencyProviderMethod.php.twig

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\{{ moduleName }}DependencyProvider"

preSpryks:
  - AddYvesDependencyProvider

postSpryks:
  - AddYvesDependencyServiceBridge
  - AddYvesDependencyServiceDependencyProviderConstant:
      arguments:
        name:
          value: "SERVICE_{{ dependentModule | underscored | upper }}"
        value:
          value:  "{{ dependentModule | camelCaseToWhitespace | lower }} service"
        visibility:
          value:  "public"

