spryk: template
description: "Adds a new *moduleName* To*dependentModule*ServiceInterface."

arguments:
  moduleName: ~
  dependentModule: ~

  organization:
    default: Spryker

  template:
    value: Yves/Dependency/Service/YvesDependencyServiceInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}ServiceInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Yves/{{ moduleName }}/Dependency/Service/"

preSpryks:
  - AddYvesDependencyServiceBridge
