spryk: method
description: "Adds a new action to the Glue controller."
mode: both

arguments:

  module:
    inherit: true

  organization:
    inherit: true
    default: Spryker

  controller:
    callback:
      - ClassNameShortCallback
      - EnsureControllerSuffixCallback

  method:
    default: "post"
    callback: EnsureActionSuffixCallback

  resourceType:
    inherit: true

  template:
    value: Glue/Controller/MethodPostGlueController.php.twig

  target:
    value: "{{ organization }}\\Glue\\{{ module }}\\Controller\\{{ controller | classNameShort | ensureControllerSuffix }}"

preSpryks:
  - AddGlueController

