mode: "core"

arguments:
  repository:
    value: "spryker/{{ organization | dasherize }}"

core:
  arguments:
    targetPath:
      value: "vendor/{{ repository }}/Bundles/"
      type: prepend

project:
  arguments:
    targetPath:
      value: "src/{{ organization }}/{{ layer }}/"
      type: prepend
