spryk: template
description: "Adds a new *moduleName* To*dependentModule*ClientInterface."

arguments:
  moduleName: ~
  dependentModule: ~

  organization:
    default: Spryker

  template:
    value: Yves/Dependency/Client/YvesDependencyClientInterface.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}ClientInterface.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Yves/{{ moduleName }}/Dependency/Client/"

preSpryks:
  - AddYvesDependencyClientBridge
