spryk: template
description: "Adds a new *module*To*dependentModule*ClientInterface."
mode: both

arguments:
  module:
    inherit: true
  dependentModule: ~

  organization:
    inherit: true
    default: Spryker

  template:
    value: Yves/Dependency/Client/YvesDependencyClientInterface.php.twig

  targetFilename:
    value: "{{ module }}To{{ dependentModule }}ClientInterface.php"

  targetPath:
    value: "{{ module }}/src/{{ organization }}/Yves/{{ module }}/Dependency/Client/"

preSpryks:
  - AddYvesDependencyClientBridge
