spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency Client bridge."

arguments:

  moduleName: ~
  organization:
    default: Spryker

  dependentModule: ~

  methods:
    type: MethodNameChoice
    choiceLoader: ClientMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - module
      - choiceLoader

  template:
    value: Yves/Dependency/YvesDependencyBridgeInterfaceMethod.php.twig

  dependencyType:
    value: Client

  sourceClass:
    value: "{{ organization }}\\Client\\{{ dependentModule }}\\{{ dependentModule }}ClientInterface"

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\Dependency\\Client\\{{ moduleName }}To{{ dependentModule }}ClientInterface"

preSpryks:
  - AddYvesDependencyClientInterface

postSpryks:
  - AddYvesDependencyClientBridgeMethod
