spryk: bridgeMethods
description: "Adds a new method to the *moduleName* dependency Client bridge."
priority: 1

arguments:

  moduleName: ~
  organization:
    default: Spryker

  dependentModule: ~

  methods:
    type: MethodNameChoice
    choiceLoader: ClientMethodChoiceLoader
    isMultiple: true
    typeOptions:
      - moduleName
      - choiceLoader

  template:
    value: Yves/Dependency/YvesDependencyBridgeMethod.php.twig

  dependencyType:
    value: Client

  sourceClass:
    value: "{{ organization }}\\Client\\{{ dependentModule }}\\{{ dependentModule }}Client"

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\Dependency\\Client\\{{ moduleName }}To{{ dependentModule }}ClientBridge"

preSpryks:
  - AddYvesDependencyClientBridge

postSpryks:
  - AddYvesDependencyClientBridgeInterfaceMethod
