spryk: method
description: "Adds a Client dependency method to the *module*Factory."

arguments:

  module: ~
  dependentModule: ~

  organization:
    default: Spryker

  method:
    value: "get{{ dependentModule }}Client"

  template:
    value: Yves/Dependency/Client/YvesDependencyClientFactoryMethod.php.twig

  target:
    value: "{{ organization }}\\Yves\\{{ module }}\\{{ module }}Factory"

preSpryks:
  - AddYvesFactory

postSpryks:
  - AddYvesDependencyClientDependencyProviderConstant:
      arguments:
        name:
          value: "CLIENT_{{ dependentModule | underscored | upper }}"
        value:
          value:  "{{ dependentModule | camelCaseToWhitespace | lower }} client"
        visibility:
          value:  "public"

