spryk: template
description: "Adds a new *moduleName*To*dependentModule*ClientBridge."

arguments:
  moduleName: ~

  organization:
    default: Spryker

  dependentModule: ~

  dependentModuleOrganization:
    default: Spryker


  template:
    value: Yves/Dependency/Client/YvesDependencyClientBridge.php.twig

  targetFilename:
    value: "{{ moduleName }}To{{ dependentModule }}ClientBridge.php"

  targetPath:
    default: "{{ moduleName }}/src/{{ organization }}/Yves/{{ moduleName }}/Dependency/Client/"

preSpryks:
  - AddSprykerModule

postSpryks:
  - AddYvesDependencyClientInterface
  - AddYvesDependencyClientFactoryMethod
  - AddYvesDependencyClientDependencyProviderMethod
  - AddYvesDependencyClientDependencyProviderConstant:
      arguments:
          name:
            value: "CLIENT_{{ dependentModule | underscored | upper }}"
          value:
            value:  "{{ dependentModule | camelCaseToWhitespace | lower }} client"
          visibility:
            value:  "public"
