spryk: method
description: "Adds a Client dependency method to the *moduleName*DependencyProvider."

arguments:

  moduleName: ~
  dependentModule: ~

  organization:
    default: Spryker

  method:
    value: "add{{ dependentModule }}Client"

  template:
    value: Yves/Dependency/Client/YvesDependencyClientDependencyProviderMethod.php.twig

  target:
    value: "{{ organization }}\\Yves\\{{ moduleName }}\\{{ moduleName }}DependencyProvider"

preSpryks:
  - AddYvesDependencyProvider

postSpryks:
  - AddYvesDependencyClientBridge
  - AddYvesDependencyClientDependencyProviderConstant:
      arguments:
        name:
          value: "CLIENT_{{ dependentModule | underscored | upper }}"
        value:
          value:  "{{ dependentModule | camelCaseToWhitespace | lower }} client"
        visibility:
          value:  "public"
