spryk: constant
description: "Adds a Client dependency constant to the *module*DependencyProvider."
mode: both

arguments:

  module:
    inherit: true
  dependentModule: ~

  organization:
    inherit: true
    default: Spryker

  name: ~
  value: ~
  visibility:
    value: "public"

  target:
    value: "{{ organization }}\\Yves\\{{ module }}\\{{ module }}DependencyProvider"

preSpryks:
  - AddYvesDependencyProvider
